steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/storyteller-449312/storyteller/storyteller-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/storyteller-449312/storyteller/storyteller-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'storyteller', '--image', 'europe-west1-docker.pkg.dev/storyteller-449312/storyteller/storyteller-image', '--region', 'europe-west1']
images:
- europe-west1-docker.pkg.dev/storyteller-449312/storyteller/storyteller-image